### ISSUE TITLE
Skip files that already exist

### ISSUE THREAD

**Issue by TheDestr0yer** [abhishekjnvk/telegram-channel-downloader#16]
Hi , first of all thank you for this fantastic project , the only problem encountered is that there is no option to skip already downloaded files , the script reports : ```File already exists: ..(name)........., Changing name``` and re-downloads everything.

**Comment by DimaMinka** [comment]
its here, lets wait for merge
https://github.com/abhishekjnvk/telegram-channel-downloader/pull/17
@TheDestr0yer
