### ISSUE TITLE
features: Download selected messages/file types only

### ISSUE THREAD

**Issue by sonicjhon1** [abhishekjnvk/telegram-channel-downloader#4]
Would be great if we could customize which files are going to be downloaded, instead of downloading every files in the chat.
Ex: *.zip, *.rar, ..etc

**Comment by abhishekjnvk** [comment]
Hello @sonicjhon1,
Thank you for your suggestion regarding the feature to download selected messages/file types. I am pleased to inform you that this feature has now been implemented.
if you encounter any issues or have further suggestions, please feel free to open a new issue.

This issue will now be closed.

Best regards,
Abhishek
